services:
  nginx: # --------------------------------------------------------------------
    ports:
      - "${PROJECT_IP:-0.0.0.0}:80:80"

  frontend: # -----------------------------------------------------------------
    build:
      context: frontend
      dockerfile: Dockerfile
      target: dev              # используем dev-стадию (см. Dockerfile ниже)
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    environment:
      - WATCHPACK_POLLING=true  # надёжный file-watching в Docker

  app: # ------------------------------------------------------------------
    volumes:
      - ./app:/app
    command:
            sh -c './manage.py collectstatic --noinput ; ./manage.py runserver 0.0.0.0:8000'
