@startuml
!include c4puml/C4_Container.puml

!include c4puml/icons/users.puml

LAYOUT_WITH_LEGEND()

Person(user, "Пользователь", "Пользователь системы", $sprite="users")

System(aist, "SYSTEM", "The main application")

System_Boundary(ords, "Foreign systems") {
    System_Ext(foreign_system, "ForeignSystem", "ForeignSystem")
    System_Ext(etc, "etc.", "Другие")
}

System_Boundary(auths, "Auths") {
    System_Ext(google_auth, "GoogleAuth", "GoogleAuth")
}

Rel(user, aist, "Uses", "https")

Rel(aist, foreign_system, "Uses", "https")
Rel_R(aist, google_auth, "Uses", "https")

@enduml
