default_stages:
-   pre-commit

exclude: /migrations/

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v5.0.0'
    hooks:
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: debug-statements
      # -   id: double-quote-string-fixer

-   repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
    -   id: black
        language_version: python3.11
        exclude: |
            (?x)^(
                i.py|
                app/core/static/core/frontend/.*|
                app/core/templates/react.app.html
            )$

-   repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        language_version: python3.11
        name: isort (python)
        exclude: i.py

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.14.0'
    hooks:
    -   id: mypy
        args: [--no-strict-optional, --install-types, --config-file=app/setup.cfg]
        exclude: i.py
        additional_dependencies: [types-requests,types-polib]

-   repo: https://github.com/pycqa/flake8
    rev: 7.2.0
    hooks:
    -   id: flake8
        language_version: python3.11
        args: [--config=app/setup.cfg]
        exclude: i.py
