# Generated by Django 5.1.11 on 2025-07-15 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата последнего изменения')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('sys_name', models.CharField(blank=True, choices=[('kokoc_group', 'Kokoc Group')], max_length=256, null=True, unique=True, verbose_name='Системное имя')),
            ],
            options={
                'verbose_name': 'Пространство',
                'verbose_name_plural': 'Пространства',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата последнего изменения')),
                ('first_name', models.CharField(blank=True, max_length=256, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=256, verbose_name='Фамилия')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Адрес электронной почты')),
                ('language', models.CharField(choices=[('ru', 'Русский'), ('en', 'English'), ('es', 'Español')], default='ru', max_length=10, verbose_name='Язык')),
                ('is_staff', models.BooleanField(default=False, help_text='Означает, что пользователь может заходить в панель администрирования.', verbose_name='Штатный сотрудник')),
                ('is_active', models.BooleanField(default=True, help_text='Означает, что пользователь может авторизоваться на сайте. Снимите галочку, чтобы пользователь не мог им пользоваться.', verbose_name='Активный')),
                ('kid_id', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='KID ID')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='core.workspace')),
            ],
            options={
                'verbose_name': 'пользователь',
                'verbose_name_plural': 'пользователи',
            },
        ),
    ]
